#!/bin/bash

#this script was written to count heterozygous and homozygous snp calls for each snp across many lines.
#it was used to determine how much heterozygosity there was per snp before and after filtering.
 
while read line
do
counts=`echo $line | grep -o "0|1" | wc -l;`
counts2=`echo $line | grep -o "1|0" | wc -l;`
counts3=`echo $line | grep -o "1|1" | wc -l;`
counts4=`echo $line | grep -o "0|0" | wc -l;`
countsHet=$(expr $counts + $counts2) 
echo "$line $counts4 $counts3 $counts $counts2 $countsHet"
done
